import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Tuple

from codex_runner import run_codex
from config import DEFAULT_BASE_BRANCH, PROMPTS_DIR, WORKER_DRY_RUN
from db import get_job, update_job_status
from github_client import GitHubClient
from workspace import cleanup_workspace, create_workspace, remove_lock


class StepError(Exception):
    def __init__(self, step: str, detail: str):
        super().__init__(f"{step}: {detail}")
        self.step = step
        self.detail = detail


def _run_cmd(step: str, cmd: list[str], cwd: Path) -> None:
    try:
        subprocess.run(cmd, cwd=cwd, check=True)
    except subprocess.CalledProcessError as exc:
        raise StepError(step, str(exc)) from exc


def _prepare_prompt(job: Dict, workspace: Path) -> Path:
    mode = (job.get("mode") or "component").strip().lower()
    if mode not in {"component", "style", "review"}:
        mode = "component"
    prompt_template = PROMPTS_DIR / f"{mode}.txt"
    payload = job.get("payload", {})
    final_prompt = workspace / "prompt.txt"
    text = (
        prompt_template.read_text(encoding="utf-8")
        + "\n\n"
        + _build_job_instruction(job, payload)
        + "\n\nWebhook payload:\n"
        + json.dumps(payload, ensure_ascii=False, indent=2)
    )
    final_prompt.write_text(text, encoding="utf-8")
    return final_prompt


def _build_job_instruction(job: Dict, payload: Dict) -> str:
    if job.get("issue_number"):
        issue = payload.get("issue") or {}
        title = issue.get("title", "")
        body = issue.get("body", "")
        labels = ", ".join(label.get("name", "") for label in issue.get("labels", []) if label.get("name"))
        return (
            "Task source: GitHub issue\n"
            f"Repository: {job['repo']}\n"
            f"Issue number: {job['issue_number']}\n"
            f"Issue title: {title}\n"
            f"Issue labels: {labels or 'none'}\n"
            "Issue body:\n"
            f"{body}\n\n"
            "Execution rules:\n"
            "- Work autonomously with no human intervention.\n"
            "- Implement the issue request end-to-end in code.\n"
            "- Run the required local validation commands and fix failures caused by your changes.\n"
            "- Keep changes minimal and production-ready.\n"
            "- Stop only when the branch is ready to be pushed and opened as a pull request."
        )

    pr = payload.get("pull_request") or {}
    return (
        "Task source: GitHub pull request\n"
        f"Repository: {job['repo']}\n"
        f"PR number: {job.get('pr_number')}\n"
        f"PR title: {pr.get('title', '')}\n"
        "PR body:\n"
        f"{pr.get('body', '')}\n\n"
        "Execution rules:\n"
        "- Work autonomously with no human intervention.\n"
        "- Review the pull request content and make only the necessary code changes.\n"
        "- Run the required local validation commands and fix failures caused by your changes.\n"
        "- Keep the branch in a merge-ready state."
    )


def _simulate_repo_changes(repo_dir: Path, job_id: str) -> None:
    repo_dir.mkdir(parents=True, exist_ok=True)
    marker = repo_dir / "DRY_RUN_RESULT.md"
    marker.write_text(
        "# Dry Run Result\n\n"
        f"job_id: {job_id}\n"
        f"generated_at: {datetime.now(timezone.utc).isoformat()}\n",
        encoding="utf-8",
    )


def _comment_success(github: GitHubClient, job: Dict, branch: str) -> None:
    body = (
        "✅ Job completed\n"
        f"Branch: {branch}\n"
        "Checks: lint/test/storybook passed"
    )
    if job.get("issue_number"):
        github.create_issue_comment(job["repo"], int(job["issue_number"]), body)
    if job.get("pr_number"):
        github.create_issue_comment(job["repo"], int(job["pr_number"]), body)


def _build_pr_title(job: Dict) -> str:
    payload = job.get("payload", {})
    issue = payload.get("issue") or {}
    issue_title = issue.get("title", "").strip()
    if issue_title:
        return f"AI: {issue_title}"
    return f"AI update for issue #{job['issue_number']}"


def _build_pr_body(job: Dict, branch: str) -> str:
    payload = job.get("payload", {})
    issue = payload.get("issue") or {}
    issue_number = job.get("issue_number")
    lines = [
        "Automated changes generated by ai-github-worker.",
        f"Source branch: `{branch}`",
    ]
    if issue_number:
        lines.append(f"Closes #{issue_number}")
    if issue.get("title"):
        lines.append("")
        lines.append(f"Issue: {issue['title']}")
    return "\n".join(lines)


def _comment_failure(github: GitHubClient, job: Dict, step: str, error: str) -> None:
    body = f"❌ Job failed\nStep: {step}\nError: {error[:500]}"
    if job.get("issue_number"):
        github.create_issue_comment(job["repo"], int(job["issue_number"]), body)
    if job.get("pr_number"):
        github.create_issue_comment(job["repo"], int(job["pr_number"]), body)


def process_job(job_id: str) -> Tuple[str, Dict]:
    job = get_job(job_id)
    if not job:
        return "failed", {"step": "load_job", "error": "job not found"}

    repo = job["repo"]
    branch = f"ai/{job_id}"
    clone_url = f"git@github.com:{repo}.git"
    workspace = create_workspace(job_id)
    repo_dir = workspace / "repo"
    github = GitHubClient()

    try:
        if WORKER_DRY_RUN:
            _prepare_prompt(job, workspace)
            _simulate_repo_changes(repo_dir, job_id)
            return "done", {
                "branch": branch,
                "checks": "dry-run simulated",
                "dry_run": True,
            }

        # 1-2. create workspace and clone repo
        _run_cmd("clone", ["git", "clone", clone_url, str(repo_dir)], cwd=workspace)

        # 3. checkout ai/{job_id}
        _run_cmd("checkout", ["git", "checkout", "-b", branch], cwd=repo_dir)

        # 4. run Codex
        prompt_file = _prepare_prompt(job, workspace)
        try:
            run_codex(prompt_file, repo_dir)
        except Exception as exc:
            raise StepError("codex", str(exc)) from exc

        # 5-8. npm checks
        _run_cmd("npm_ci", ["npm", "ci"], cwd=repo_dir)
        _run_cmd("lint", ["npm", "run", "lint"], cwd=repo_dir)
        _run_cmd("test", ["npm", "test", "--", "--watch=false"], cwd=repo_dir)
        _run_cmd("storybook", ["npm", "run", "build-storybook"], cwd=repo_dir)

        # 9. commit + push
        _run_cmd("git_add", ["git", "add", "-A"], cwd=repo_dir)
        commit_msg = f"chore(ai): apply codex updates for {job_id}"
        diff_check = subprocess.run(
            ["git", "diff", "--cached", "--quiet"],
            cwd=repo_dir,
            check=False,
        )
        if diff_check.returncode == 0:
            raise StepError("git_commit", "no code changes produced for pull request")
        _run_cmd("git_commit", ["git", "commit", "-m", commit_msg], cwd=repo_dir)
        _run_cmd("git_push", ["git", "push", "-u", "origin", branch], cwd=repo_dir)

        # 10. comment / PR
        pr_url = None
        if job.get("issue_number"):
            pr_response = github.create_pull_request(
                repo=repo,
                title=_build_pr_title(job),
                head=branch,
                base=DEFAULT_BASE_BRANCH,
                body=_build_pr_body(job, branch),
            )
            pr_url = pr_response.get("html_url")
        _comment_success(github, job, branch)

        result = {"branch": branch, "checks": "lint/test/storybook passed"}
        if pr_url:
            result["pr_url"] = pr_url
        return "done", result
    except StepError as exc:
        try:
            _comment_failure(github, job, exc.step, exc.detail)
        except Exception:
            pass
        return "failed", {"step": exc.step, "error": exc.detail}
    except Exception as exc:
        try:
            _comment_failure(github, job, "unexpected", str(exc))
        except Exception:
            pass
        return "failed", {"step": "unexpected", "error": str(exc)}
    finally:
        cleanup_workspace(workspace)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--job-id", required=True)
    args = parser.parse_args()

    status = "failed"
    result: Dict = {}
    try:
        status, result = process_job(args.job_id)
        update_job_status(args.job_id, status, result)
    finally:
        # 12-13. lock removal and cleanup are guaranteed on worker exit.
        remove_lock()


if __name__ == "__main__":
    main()
